/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ItemsCatalogService } from "../itemsCatalog.service";
import { ItemsCatalogCreateInput } from "./ItemsCatalogCreateInput";
import { ItemsCatalog } from "./ItemsCatalog";
import { ItemsCatalogFindManyArgs } from "./ItemsCatalogFindManyArgs";
import { ItemsCatalogWhereUniqueInput } from "./ItemsCatalogWhereUniqueInput";
import { ItemsCatalogUpdateInput } from "./ItemsCatalogUpdateInput";
import { TransactionsFindManyArgs } from "../../transactions/base/TransactionsFindManyArgs";
import { Transactions } from "../../transactions/base/Transactions";
import { TransactionsWhereUniqueInput } from "../../transactions/base/TransactionsWhereUniqueInput";

export class ItemsCatalogControllerBase {
  constructor(protected readonly service: ItemsCatalogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ItemsCatalog })
  async createItemsCatalog(
    @common.Body() data: ItemsCatalogCreateInput
  ): Promise<ItemsCatalog> {
    return await this.service.createItemsCatalog({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        sku: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ItemsCatalog] })
  @ApiNestedQuery(ItemsCatalogFindManyArgs)
  async itemsCatalogs(@common.Req() request: Request): Promise<ItemsCatalog[]> {
    const args = plainToClass(ItemsCatalogFindManyArgs, request.query);
    return this.service.itemsCatalogs({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        sku: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ItemsCatalog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async itemsCatalog(
    @common.Param() params: ItemsCatalogWhereUniqueInput
  ): Promise<ItemsCatalog | null> {
    const result = await this.service.itemsCatalog({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        sku: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ItemsCatalog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateItemsCatalog(
    @common.Param() params: ItemsCatalogWhereUniqueInput,
    @common.Body() data: ItemsCatalogUpdateInput
  ): Promise<ItemsCatalog | null> {
    try {
      return await this.service.updateItemsCatalog({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          sku: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ItemsCatalog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteItemsCatalog(
    @common.Param() params: ItemsCatalogWhereUniqueInput
  ): Promise<ItemsCatalog | null> {
    try {
      return await this.service.deleteItemsCatalog({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          sku: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactionsItems")
  @ApiNestedQuery(TransactionsFindManyArgs)
  async findTransactionsItems(
    @common.Req() request: Request,
    @common.Param() params: ItemsCatalogWhereUniqueInput
  ): Promise<Transactions[]> {
    const query = plainToClass(TransactionsFindManyArgs, request.query);
    const results = await this.service.findTransactionsItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        dateTime: true,
        id: true,

        itemsCatalog: {
          select: {
            id: true,
          },
        },

        quantity: true,
        typeField: true,
        updatedAt: true,

        warehouse: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactionsItems")
  async connectTransactionsItems(
    @common.Param() params: ItemsCatalogWhereUniqueInput,
    @common.Body() body: TransactionsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionsItems: {
        connect: body,
      },
    };
    await this.service.updateItemsCatalog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactionsItems")
  async updateTransactionsItems(
    @common.Param() params: ItemsCatalogWhereUniqueInput,
    @common.Body() body: TransactionsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionsItems: {
        set: body,
      },
    };
    await this.service.updateItemsCatalog({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactionsItems")
  async disconnectTransactionsItems(
    @common.Param() params: ItemsCatalogWhereUniqueInput,
    @common.Body() body: TransactionsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactionsItems: {
        disconnect: body,
      },
    };
    await this.service.updateItemsCatalog({
      where: params,
      data,
      select: { id: true },
    });
  }
}
